---
#-------------------------------
# General Site Settings

menu:
  - { name: "Portfolio", url: "" }
  - { name: "Blog", url: "blog" }
  - { name: "About", url: "about" }
  - { name: "Contact", url: "contact" }

#-------------------------------
# Projects Section

projects:
  - { name: "Por un punyado de peluches", url: "por-un-punyado-de-peluches" }
  - { name: "Project Two", url: "proj-2" }
  - { name: "Project Three", url: "proj-3" }
  - { name: "Project Four", url: "proj-4" }
  - { name: "Project Five", url: "proj-5" }

#-------------------------------
# Contact Section

social:
  #- { icon: "twitter", link: "https://twitter.com/paululele" }
  - { icon: "instagram", link: "https://instagram.com/niaveser" }
  - { icon: "github", link: "https://github.com/niaveser" }
  - {
      icon: "linkedin",
      link: "www.linkedin.com/in/nia-robles-content-specialist",
    }
  - { icon: "envelope", link: "mailto:mailto:nia.robles.art@gmail.com" }

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: "Personal portfolio powered by Jekyll and GitHub Pages "
  rel-author: "https://plus.google.com/u/0/#"
  rel-publisher: "https://plus.google.com/u/0/#"

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: "UA-112060364-3"

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ""
