---
#-------------------------------
# General Site Settings

menu:
  - { name: "Portfolio", url: "" }
  - { name: "Blog", url: "blog" }
  - { name: "About", url: "about" }
  - { name: "Contact", url: "contact" }

#-------------------------------
# Projects Section

projects:
  - {
      name: "Strategic UX Research",
      url: "strategic-ux-research",
      category: UX/UI,
      skills: "Research,
        Wireframes,
        Figma",
    }
  - {
      name: "Social Media Management",
      url: "social-media-management",
      category: social-media,
      skills: "Instagram,
        Organic Growth,
        Content Creation",
    }
  - {
      name: "Content Creation",
      url: "content-creation",
      category: social-media,
    }
  - {
      name: "Por un punyado de peluches",
      url: "por-un-punyado-de-peluches",
      category: art-design,
      skills: "Characters, Props, Design, Color Theory",
    }
  - {
      name: "Cute illustrations",
      url: "cute-illustrations",
      category: art-design,
      skills: "Color Theory,
        Composition",
    }
  - {
      name: "Awaq ONGD: Logo and banner",
      url: "awaq-ongd-logo-and-banner",
      category: art-design,
      skills: "Illustrator,
        Color Theory,
        Branding",
    }
  - {
      name: "Advice Generator",
      url: "advice-generator",
      category: coding,
      skills: "React, Flexbox, API Consuming",
    }
  - {
      name: "Sunnyside Agency Landing Page",
      url: "sunnyside-agency-landing-page",
      category: coding,
      skills: "Semantic HTML5 Markup,
        Flexbox,
        CSS Grid,
        JavaScript,
        Responsive Design",
    }

#-------------------------------
# Contact Section

social:
  - { icon: "instagram", link: "https://instagram.com/niaveser" }
  - { icon: "github", link: "https://github.com/niarobles-design" }
  - { icon: "linkedin", link: "www.linkedin.com/in/nia-robles-visual-designer" }
  - { icon: "envelope", link: "mailto:mailto:nia.robles.art@gmail.com" }

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: "UX Design and Social Media Portfolio "
  rel-author: "https://plus.google.com/u/0/#"
  rel-publisher: "https://plus.google.com/u/0/#"

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: "UA-112060364-3"

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ""
